Create TaskManager
Ewan10/Task-Manager pull request #1
Opened 2021-05-21 12:13 UTC by Ewan10

2021-05-21 13:41 UTC, thompsy commented
It would be good practice to run some basic formatting and linting on your code. Here's a bit of an intro to how you could do some of this with VS Code: https://code.visualstudio.com/docs/java/java-linting

2021-05-21 13:43 UTC, thompsy commented
It would also be worth updating the name of the file to include the `.java` extension. This allows tools like Github to recognise what language it is and do syntax highlighting automatically.

2021-05-21 13:47 UTC, thompsy commented
You might want to look at using Maven to build the project. This should be a good place to start: http://maven.apache.org/guides/getting-started/maven-in-five-minutes.html

2021-05-24 10:22 UTC, thompsy requested changes

2021-05-24 10:25 UTC, thompsy commented
One more note for now: it would be worth updating your comments. The long dashes aren't really necessary. This page has some sensible guidance for good coding practices generally and for commenting specifically: https://www.baeldung.com/java-clean-code

2021-05-27 18:08 UTC, Ewan10 commented on TaskManager.java
> +	public boolean DateComparison(String date) {
I will revise the date and time classes. Of course.

2021-05-27 18:09 UTC, Ewan10 commented on TaskManager.java
> +    private String date;
I got to do revision on the date/time classes for java and amend those parts.

2021-05-27 18:10 UTC, Ewan10 commented on TaskManager.java
> +    public void  ChangeDate() {
I 'll fix that as well. I agree to conform with the convention.

2021-05-27 18:13 UTC, Ewan10 commented on TaskManager.java
> +          while(true) {
I already studied the command line parsing from apache commons. I am aware of the definition stage, the parsing stage and the interrogations stage by creating an Options object, DefaultParser, adding options and checking the user input.

2021-05-27 18:16 UTC, Ewan10 commented on TaskManager.java
> +          while(true) {
I have noted down all the points for improvement. The use of the date/time class, the separation of concerns for two methods which I noticed during the development and debugging phase, the apppropriate naming also for various variables and methods, the command line parsing and the permanent storage of the tasks. I 'll work on each of them step by step and I 'll upload a new version of the project.

2021-05-27 18:17 UTC, Ewan10 commented on TaskManager.java
> +            ta.setTitle(" -Done.");
I can create a new field. I will change it.

2021-05-27 18:18 UTC, Ewan10 commented on TaskManager.java
> +    public void All() {
I 'll just rename it viewAllTasks().

2021-05-27 18:19 UTC, Ewan10 commented on TaskManager.java
> +    private String title;
I 'll just remove them.

2021-05-27 20:17 UTC, thompsy commented on TaskManager.java
> +          while(true) {
Sounds good! I'm looking forward to seeing it 👍

2021-07-18 17:59 UTC, merged