Refactoring of add, view, save and load methods
Ewan10/Task-Manager pull request #9
Opened 2022-01-25 08:29 UTC by Ewan10

First refactoring of add, view, save and load methods.

2022-01-25 09:10 UTC, thompsy commented on src/main/java/com/ewan/TaskManager/Main.java
> +//import java.io.FileNotFoundException;
You can remove all of these commented out lines. Part of the reason for keeping things in Git, is that our past code is always available if we need to go back and view it later.

Basically, there should never be any commented out lines in files you commit.

2022-01-25 09:12 UTC, thompsy commented on src/main/java/com/ewan/TaskManager/Main.java
> +    options.addOption("a", "add", true, "add new task")
It would be better to use a single convention here. So, in lines 34-36 you are chaining the calls to `addOption`, but then in lines 37-38 you use the longer form of `options.addOption`. Either approach is fine, but it is better to stick to one.

2022-01-25 09:16 UTC, thompsy commented on src/main/java/com/ewan/TaskManager/Main.java
> +    if (cmd.hasOption("time")) {
The problem with this approach is that if the user does not provide a title or date, we'll still create a task but it will only have a time. This probably isn't very useful from a user perspective.

Perhaps try checking for the existence of the title, date and time in a single condition, that way you can be confident that the user has provided all the required information. This also means you can get rid of the variables in line 42-44.

Something like this:
`if (cmd.hasOption("add") && cmd.hasOption("date") && cmd.hasOption("time")} {...}`

2022-01-25 09:17 UTC, thompsy commented on src/main/java/com/ewan/TaskManager/TaskManager.java
>  class TaskManager implements Serializable {
This probably doesn't need to implement the `Serializable` interface any more since we're never serializing it.

2022-01-25 09:18 UTC, thompsy commented on src/main/java/com/ewan/TaskManager/TaskManager.java
> +  private List<Task> getTaskStorage() {
You don't really need this method at all. It's a private method so any the underlying `taskStorage` will be accessible wherever you were calling this.

2022-01-25 09:19 UTC, thompsy commented on src/main/java/com/ewan/TaskManager/TaskManager.java
> +        String jsonObjectAsString = jsonObject.toJson(getTaskStorage());
As above, you don't need the `getTaskStorage()` method. You can just access `taskStorage` directly.

2022-01-25 09:21 UTC, thompsy commented on src/main/java/com/ewan/TaskManager/TaskManager.java
> +      String oneLine= null;
I would move this declaration down into the `try` block. It's best to keep the scope of variables as small as is required. Since `oneLine` is only used within the `try` block we should just declare it there.

2022-01-25 09:22 UTC, thompsy commented on src/main/java/com/ewan/TaskManager/TaskManager.java
> +      String lines="";
You should try and use a consistent formatting. Here you don't have any whitespace around the `=` but in most other places you do. It's a good habit to format the files before you commit. I think in VSCode you can run the `Format this document` command.

2022-01-25 09:25 UTC, thompsy requested changes
I've make a few comments below that need your input. 

In terms of the files under the `target` directory and also the `TaskWarehouse.txt` file, you should remove them using `git rm` and then add a `.gitignore` file. You can see some details here: https://www.atlassian.com/git/tutorials/saving-changes/gitignore

If you make those changes to this branch and then push again, that should update the PR.

2022-01-25 09:32 UTC, thompsy commented on src/main/java/com/ewan/TaskManager/TaskManager.java
>    /***
We can get rid of the `complete` method for now too.

2022-01-25 09:33 UTC, thompsy commented on src/main/java/com/ewan/TaskManager/TaskManager.java
>     * The userInput() method prints an expression for
We can get rid of the `userInput` method too.

2022-01-25 09:46 UTC, thompsy commented on src/main/java/com/ewan/TaskManager/TaskManager.java
>    private List<Task> taskStorage = new ArrayList<Task>();
This field should be declared as `final` since it shouldn't change.

2022-01-25 09:50 UTC, thompsy commented on src/main/java/com/ewan/TaskManager/Main.java
> +    if (cmd.hasOption("save")) {
We probably want to save by default. If a user adds a task they almost certainly want it to be saved otherwise why would they add it?

2022-01-25 09:51 UTC, thompsy commented on src/main/java/com/ewan/TaskManager/TaskManager.java
> +      this.taskStorage = listOfTasks;
Probably better to use `taskStorage.addAll(listOfTasks)` rather than assigning to `taskStorage`. This allows us to declare `taskStorage` as `final` which is good practice.

2022-01-25 10:13 UTC, thompsy commented on src/main/java/com/ewan/TaskManager/Main.java
>      TaskManager T1 = new TaskManager();
It would be worth changing the name of this field. `T1` is not a very descriptive term and perhaps suggest that there's going to be a `T2`. I suggest you change this name to be `taskManager` as that better describes what it is.

2022-01-27 07:06 UTC, Ewan10 commented on src/main/java/com/ewan/TaskManager/Main.java
> +//import java.io.FileNotFoundException;
Let' s start tiding up the files.

2022-01-27 07:25 UTC, Ewan10 commented on src/main/java/com/ewan/TaskManager/TaskManager.java
>    private List<Task> taskStorage = new ArrayList<Task>();
Should I declare taskStorage as final? Doesn' t this field's value change when we add a new task?

2022-01-27 07:37 UTC, Ewan10 commented on src/main/java/com/ewan/TaskManager/Main.java
> +    options.addOption("a", "add", true, "add new task")
I corrected it.

2022-01-27 07:40 UTC, Ewan10 commented on src/main/java/com/ewan/TaskManager/TaskManager.java
>    /***
I removed it!

2022-01-27 07:40 UTC, Ewan10 commented on src/main/java/com/ewan/TaskManager/Main.java
> +    if (cmd.hasOption("save")) {
Done!

2022-01-27 07:41 UTC, Ewan10 commented on src/main/java/com/ewan/TaskManager/Main.java
>      TaskManager T1 = new TaskManager();
Done!

2022-01-27 07:41 UTC, Ewan10 commented
The pull request has been updated.

2022-01-27 07:43 UTC, Ewan10 commented on src/main/java/com/ewan/TaskManager/TaskManager.java
> +      String lines="";
It has been corrected as requested.

2022-01-27 10:06 UTC, thompsy commented on src/main/java/com/ewan/TaskManager/TaskManager.java
>    private List<Task> taskStorage = new ArrayList<Task>();
Good question! When the `taskStorage` field is `final` this means that it will always point to the same list. The contents of the list can change e.g. we can add and remove items, but it can never point to another list. 

There are cases when we want a list that never changes. In that case we would use an immutable list.

2022-01-27 10:09 UTC, thompsy requested changes
That looks great Ioannis, good work. One last thing: you should add the `.gitignore` file to the repo too so that it's under version control.

2022-01-27 17:44 UTC, thompsy requested changes
One more change here. Your `.gitignore` file has some absolute paths in it. This means that it will only work on your machine but if someone else clones the repo they will obviously have a different path than you so those directories won't be ignored. 

Once you update these paths to be relative to the main project directory you should be good to go. So, it should look something like this:
```
target
.vscode
```

2022-01-27 20:42 UTC, thompsy approved these changes
Looks good Ioannis! Feel free to merge it!

2022-01-28 09:02 UTC, merged